services:
  # NavImpact Backend API
  - type: web
    name: navimpact-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: navimpact-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://navimpact-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://navimpact-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: EMAIL_SERVER
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: VERSION
        value: "1.0.0"

  # NavImpact Frontend
  - type: web
    name: navimpact-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://navimpact-api.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: NavImpact
      - key: NEXT_PUBLIC_APP_DESCRIPTION
        value: NavImpactV2 - Intelligent Grant Matching Platform
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html

databases:
  - name: navimpact-db
    databaseName: navimpact
    user: navimpact_user
    plan: starter 