services:
  # Backend API Service
  - type: web
    name: sge-dashboard-api
    env: python
    buildCommand: |
      # Print initial environment state
      echo "Current working directory: $(pwd)"
      echo "Listing all .env files:"
      find . -name ".env*" -type f
      
      # Upgrade pip and install requirements
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      # Remove any .env files to prevent environment variable conflicts
      find . -name ".env*" -type f -delete
      echo "Removed any existing .env files"
      
      # Install optional security packages
      pip install slowapi[redis] sentry-sdk[fastapi] psycopg2-binary || echo "Optional packages not installed"
      
      # Print detailed environment check
      echo "=== Environment Variable Check ==="
      python -c "
import os
import json
import socket

def check_env():
    print('ENVIRONMENT:', os.getenv('ENVIRONMENT', 'not set'))
    print('RENDER:', os.getenv('RENDER', 'not set'))
    db_url = os.getenv('DATABASE_URL', 'not set')
    print('DATABASE_URL type:', db_url.split('://')[0] if '://' in db_url else 'invalid')
    if '@' in db_url:
        host = db_url.split('@')[1].split('/')[0]
        try:
            ip = socket.gethostbyname(host)
            print(f'Database host {host} resolves to {ip}')
        except:
            print(f'Could not resolve database host {host}')

check_env()
"
    startCommand: |
      echo "=== Starting backend deployment ==="
      echo "Environment check:"
      python -c "
import os
print('ENVIRONMENT:', os.getenv('ENVIRONMENT', 'not set'))
print('RENDER:', os.getenv('RENDER', 'not set'))
print('DATABASE_URL type:', os.getenv('DATABASE_URL', 'not set').split('://')[0] if '://' in os.getenv('DATABASE_URL', '') else 'invalid')
"
      alembic upgrade head || echo "Database migration failed, continuing..."
      gunicorn app.main:app \
        --workers 2 \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --timeout 300 \
        --keep-alive 120 \
        --max-requests 1000 \
        --max-requests-jitter 50 \
        --worker-tmp-dir /dev/shm \
        --graceful-timeout 120 \
        --preload \
        --log-level debug \
        --error-logfile - \
        --access-logfile - \
        --capture-output \
        --statsd-host localhost:8125 \
        --worker-connections 1000
    envVars:
      # Core Environment
      - key: RENDER
        value: "true"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONUNBUFFERED
        value: "1"
      
      # Database Configuration
      - key: DATABASE_URL
        sync: false  # Set this manually in the dashboard
      - key: DATABASE_SSL_MODE
        value: "require"
      - key: DATABASE_POOL_SIZE
        value: "2"  # Reduced for stability
      - key: DATABASE_MAX_OVERFLOW
        value: "5"  # Reduced for stability
      - key: DATABASE_POOL_TIMEOUT
        value: "30"
      - key: DATABASE_POOL_RECYCLE
        value: "1800"
      - key: DATABASE_MAX_RETRIES
        value: "5"  # Increased retries
      - key: DATABASE_RETRY_DELAY
        value: "5"  # Increased delay
      - key: DATABASE_ECHO
        value: "false"
      - key: PGCONNECT_TIMEOUT
        value: "10"
      - key: PGSSLMODE
        value: "require"
      - key: PGDATESTYLE
        value: "ISO, MDY"
      - key: PGTZ
        value: "UTC"
      - key: PGCLIENTENCODING
        value: "UTF8"
      - key: PGAPPNAME
        value: "sge-dashboard-api"
      
      # Security - Generated or set manually
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      
      # Supabase - Set manually from your Supabase project
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      
      # CORS Configuration
      - key: FRONTEND_URL
        value: "https://sge-dashboard-web.onrender.com"
      - key: CORS_ORIGINS
        value: '["https://sge-dashboard-web.onrender.com", "https://*.onrender.com"]'
      
      # Rate Limiting
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: "60"
      - key: RATE_LIMIT_REQUESTS_PER_HOUR
        value: "1000"
      
      # Monitoring (set manually if using Sentry)
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: "production"
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: "1.0"
      
      # Email Configuration (set manually if using email)
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAILS_FROM_EMAIL
        sync: false
      - key: EMAILS_FROM_NAME
        sync: false
      
    healthCheckPath: /health
    autoDeploy: false  # Manual deployment for security
    scaling:
      minInstances: 1
      maxInstances: 2  # Allow scaling for production
      targetMemoryPercent: 70
      targetCPUPercent: 70
    
  # Frontend Service
  - type: web
    name: sge-dashboard-web
    env: node
    buildCommand: |
      cd frontend
      npm ci --only=production
      npm run build
      # Copy public files to standalone directory
      cp -r .next/static .next/standalone/.next/
      cp -r public .next/standalone/
    startCommand: |
      cd frontend/.next/standalone
      PORT=$PORT node server.js
    envVars:
      # Backend API URL
      - key: NEXT_PUBLIC_API_URL
        value: "https://sge-dashboard-api.onrender.com"
      
      # Environment
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_ENV
        value: production
      
      # Port configuration
      - key: PORT
        value: "3000"
      
      # Security Settings
      - key: NEXT_PUBLIC_ENABLE_ANALYTICS
        value: "false"
      - key: NEXT_PUBLIC_DEBUG_MODE
        value: "false"
      
      # Supabase Frontend Keys (public keys only)
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      
    healthCheckPath: /
    autoDeploy: false  # Manual deployment for security
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70
    
    # Security Headers (additional layer)
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=(), payment=()

# Environment Groups for organized configuration
envVarGroups:
  - name: production-security
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: DATABASE_ECHO
        value: "false"
      - key: RATE_LIMIT_ENABLED
        value: "true" 