services:
  # Backend API Service
  - type: web
    name: navimpact-api
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: |
      echo "Starting backend deployment..."
      echo "Database URL: $DATABASE_URL"
      alembic upgrade head || echo "Migration failed, continuing..."
      gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --timeout 300 --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        fromDatabase:
          name: navimpact-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://navimpact.onrender.com,https://navimpact-frontend.onrender.com"
      - key: ALLOWED_HOSTS
        value: "navimpact-api.onrender.com,localhost,127.0.0.1"
      - key: LOG_LEVEL
        value: INFO
      - key: EMAIL_ENABLED
        value: "false"
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: MAX_REQUESTS_PER_MINUTE
        value: "60"
      - key: DATABASE_POOL_SIZE
        value: "10"
      - key: DATABASE_MAX_OVERFLOW
        value: "20"
      - key: DATABASE_POOL_TIMEOUT
        value: "30"
      - key: DATABASE_POOL_RECYCLE
        value: "3600"

  # Frontend Service
  - type: web
    name: navimpact-frontend
    env: node
    nodeVersion: "20.x"
    buildCommand: |
      cd frontend
      npm ci --only=production
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://navimpact-api.onrender.com
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

databases:
  - name: navimpact-db
    databaseName: navimpact
    user: navimpact 