services:
  # Backend API - Deploy First
  - type: web
    name: navimpact-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: navimpact-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web - Deploy After Backend
  - type: web
    name: navimpact-web
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build:force-dynamic
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://navimpact-api.onrender.com
      - key: NEXT_DISABLE_STATIC_GENERATION
        value: "true"
      - key: NEXT_FORCE_DYNAMIC
        value: "true"
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: navimpact-db
    env: postgresql
    plan: starter
    ipAllowList: [] 