services:
  # Backend API Service for SGE
  - type: web
    name: shadow-goose-api
    branch: sge
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --only-binary::all: --prefer-binary -r requirements.txt
    startCommand: |
      echo "Starting SGE backend deployment..."
      echo "Database URL: $DATABASE_URL"
      echo "Running fresh database migrations..."
      alembic upgrade head
      gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --timeout 300 --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        value: postgresql://navimpact_dbv3_user:EY0Vd5QcTEoY7ZM0CrKCWfsFVHcYIZ8V@dpg-d21hvsvfte5s73fkk140-a/navimpact_dbv3
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://shadow-goose-dashboard.onrender.com"
      - key: ALLOWED_HOSTS
        value: "shadow-goose-api.onrender.com,localhost,127.0.0.1"
      - key: LOG_LEVEL
        value: INFO
      - key: EMAIL_ENABLED
        value: "false"
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: MAX_REQUESTS_PER_MINUTE
        value: "60"
      - key: DATABASE_POOL_SIZE
        value: "5"
      - key: DATABASE_MAX_OVERFLOW
        value: "10"
      - key: DATABASE_POOL_TIMEOUT
        value: "30"
      - key: DATABASE_POOL_RECYCLE
        value: "1800"

  # Frontend Service for SGE
  - type: web
    name: shadow-goose-dashboard
    branch: sge
    env: node
    nodeVersion: "20.x"
    buildCommand: |
      cd frontend
      npm ci
      npm run build
      echo "Build completed, static files in out/ directory"
    startCommand: |
      cd frontend
      npx serve@latest out -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shadow-goose-api.onrender.com
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"

databases:
  - name: NavImpact-dbV3
    databaseName: navimpact
    user: navimpact 