services:
  # Backend API Service
  - type: web
    name: sge-dashboard-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      # Core Environment
      - key: RENDER
        value: "true"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONUNBUFFERED
        value: "1"
      
      # Database Configuration
      - key: DATABASE_URL
        sync: false  # Set this manually in the dashboard
      
      # Security - Generated or set manually
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      
      # CORS Configuration
      - key: FRONTEND_URL
        value: "https://sge-dashboard-web.onrender.com"
      - key: CORS_ORIGINS
        value: '["https://sge-dashboard-web.onrender.com", "https://sge-dashboard-api.onrender.com", "https://*.onrender.com"]'
      
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70
    
  # Frontend Service
  - type: web
    name: sge-dashboard-web
    env: node
    rootDir: frontend
    buildCommand: |
      npm ci --only=production
      npm run build
    startCommand: |
      npm start
    envVars:
      # Environment
      - key: NODE_ENV
        value: production
      # Backend API URL
      - key: NEXT_PUBLIC_API_URL
        value: "https://sge-dashboard-api.onrender.com"
    
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70

# Environment Groups for organized configuration
envVarGroups:
  - name: production-security
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: DATABASE_ECHO
        value: "false"
      - key: RATE_LIMIT_ENABLED
        value: "true" 