#!/bin/bash

# NavImpact V2 - Fix Host Header and Data Issues
# This script fixes the "Invalid host header" error and ensures proper data flow

echo "🔧 FIXING HOST HEADER AND DATA ISSUES"
echo "====================================="
echo ""

echo "✅ PROGRESS: Database migrations working"
echo "❌ CURRENT ISSUE: Backend returning 'Invalid host header'"
echo "❌ RESULT: Frontend can't get data from API"
echo ""

echo "🔧 ROOT CAUSE:"
echo "=============="
echo "• Backend ALLOWED_HOSTS not configured properly"
echo "• Frontend requests being rejected"
echo "• No data flow between frontend and backend"
echo ""

echo "📋 COMPREHENSIVE FIX REQUIRED:"
echo "=============================="
echo ""
echo "1. Fix backend ALLOWED_HOSTS configuration"
echo "2. Ensure database migrations complete successfully"
echo "3. Test API endpoints return proper data"
echo "4. Verify frontend can communicate with backend"
echo ""

echo "🔧 MANUAL FIX STEPS:"
echo "===================="
echo ""
echo "STEP 1: Fix Backend Host Configuration"
echo "====================================="
echo "1. Go to: https://dashboard.render.com"
echo "2. Find: navimpact-api-staging service"
echo "3. Go to: Settings → Environment"
echo "4. Find: ALLOWED_HOSTS variable"
echo "5. Set it to: navimpact-api-staging.onrender.com,localhost,127.0.0.1,*"
echo "6. Click 'Save Changes'"
echo ""
echo "STEP 2: Update Start Command"
echo "==========================="
echo "1. Go to: Settings → Build & Deploy"
echo "2. Find: Start Command field"
echo "3. Replace with this COMPLETE command:"
echo ""
echo "echo 'Starting STAGING backend deployment...' && echo 'Database URL: $DATABASE_URL' && echo 'Stamping database head...' && alembic stamp 20250127_sustainability && echo 'Running database migrations...' && alembic upgrade 20250127_sustainability && echo 'Starting application...' && gunicorn app.main:app --bind 0.0.0.0:\$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --timeout 300 --preload"
echo ""
echo "4. Click 'Save Changes'"
echo "5. Go to 'Manual Deploy' section"
echo "6. Click 'Deploy latest commit'"
echo ""

echo "🔍 WHAT THIS FIXES:"
echo "==================="
echo "• ALLOWED_HOSTS accepts frontend requests"
echo "• Database migrations complete successfully"
echo "• API endpoints return proper data"
echo "• Frontend can communicate with backend"
echo ""

echo "⏱️ EXPECTED TIMELINE:"
echo "====================="
echo "• Environment variable update: 1 minute"
echo "• Backend redeployment: 5-8 minutes"
echo "• Database migration: 2-3 minutes"
echo "• Full system test: 10-15 minutes"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "====================="
echo "• Backend returns 200 OK (not 'Invalid host header')"
echo "• API endpoints return data (not errors)"
echo "• Frontend can load grant details"
echo "• All database tables exist and populated"
echo ""

echo "🎯 TESTING COMMANDS:"
echo "==================="
echo "After deployment, test with:"
echo ""
echo "1. Backend health:"
echo "   curl https://navimpact-api-staging.onrender.com/health"
echo ""
echo "2. API endpoints:"
echo "   curl https://navimpact-api-staging.onrender.com/api/v1/users"
echo "   curl https://navimpact-api-staging.onrender.com/api/v1/projects"
echo "   curl https://navimpact-api-staging.onrender.com/api/v1/grants"
echo ""
echo "3. Frontend test:"
echo "   Visit: https://navimpact-web-staging.onrender.com/grants/apply/1/"
echo ""

echo ""
echo "✅ COMPREHENSIVE FIX SCRIPT COMPLETE"
echo "===================================="
echo ""
echo "Next action: Apply both fixes (ALLOWED_HOSTS + Start Command)"
echo "" 